### PR TITLE
Update .jshintrc file to match style guide

### PR DESCRIPTION
**Pull request by dbaq**
Required change to match the style guide mentioned in https://github.com/hmecookd/HomeCooked/issues/8.

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
Seems good, let me test it locally and I'll merge if all seems good!

**Comment by dbaq** [comment]
It doesnt change anything locally, just the jshint task won't pass because we need to "migrate" the current code to this new code style. You just have to use --force option with grunt serve.

**Comment by valdrinkoshi** [comment]
How do you prefer to proceed, fix the style in this PR or do it separately on another PR? I'd say on this PR

**Comment by valdrinkoshi** [comment]
Otherwise having the "standard" style rules is good with me

**Comment by dbaq** [comment]
I am going to do it on this PR :)

**Comment by valdrinkoshi** [comment]
please update also the package.json with the latest version of jshint (the current one has a lot of false messages)
Update with this command
npm install grunt-contrib-jshint@0.11.2 --save-dev
it should update the package.json (see the diff to be sure)

**Pull request merged**
